name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Restore dependencies
      run: dotnet restore

    - name: List files before build
      run: ls -R

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: List files after build
      run: ls -R

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
